services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    Owp\OwpEntry\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    service.entry:
        class: Owp\OwpEntry\Service\EntryService
        public: true

    service.people:
        class: Owp\OwpEntry\Service\PeopleService
        public: true

    service.team:
        class: Owp\OwpEntry\Service\TeamService
        public: true

    manager.entry.open:
        class: Owp\OwpEntry\Manager\OpenEntryManager
        public: true

    manager.entry.club:
        class: Owp\OwpEntry\Manager\ClubEntryManager
        public: true

    manager.entry.team:
        class: Owp\OwpEntry\Manager\TeamEntryManager
        public: true
